server:
  port: 8090
  ssl:
    key-store: classpath:redcrosstest.asia.jks
    key-store-password: oxfp8627
    key-store-type: JKS
spring:
  application:
    name: RedCross
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
#    username: root
    username: demo
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    port: 587
    username: 2572886630@qq.com
    password: admbwnjafrwueabc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 Mapper XML 文件的位置
  type-aliases-package: com.example.redcross.entity # 实体类所在的包
  configuration:
    map-underscore-to-camel-case: true
#sql语句显示
logging:
  level:
    com.example.redcross.mapper: DEBUG
    com.example.redcross: INFO
  file:
#    name: d:/DeskTop/Red Cross/logs/redcross.log
    name: /home/redcrossLogs/redcross.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
#      file-name-pattern: d:/DeskTop/Red Cross/logs/redcross-%d{yyyy-MM-dd}.%i.log
      file-name-pattern: /home/redcrossLogs/redcross-%d{yyyy-MM-dd}.%i.log